package com.idx.aidldemo.bean.score;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCORE".
*/
public class ScoreDao extends AbstractDao<Score, Long> {

    public static final String TABLENAME = "SCORE";

    /**
     * Properties of entity Score.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Score_id = new Property(0, Long.class, "score_id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Score = new Property(2, int.class, "score", false, "SCORE");
        public final static Property StudentId = new Property(3, Long.class, "studentId", false, "STUDENT_ID");
    }

    private Query<Score> student_ScoresQuery;

    public ScoreDao(DaoConfig config) {
        super(config);
    }
    
    public ScoreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCORE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: score_id
                "\"TYPE\" TEXT," + // 1: type
                "\"SCORE\" INTEGER NOT NULL ," + // 2: score
                "\"STUDENT_ID\" INTEGER);"); // 3: studentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCORE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Score entity) {
        stmt.clearBindings();
 
        Long score_id = entity.getScore_id();
        if (score_id != null) {
            stmt.bindLong(1, score_id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getScore());
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(4, studentId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Score entity) {
        stmt.clearBindings();
 
        Long score_id = entity.getScore_id();
        if (score_id != null) {
            stmt.bindLong(1, score_id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getScore());
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(4, studentId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Score readEntity(Cursor cursor, int offset) {
        Score entity = new Score( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // score_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.getInt(offset + 2), // score
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // studentId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Score entity, int offset) {
        entity.setScore_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setScore(cursor.getInt(offset + 2));
        entity.setStudentId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Score entity, long rowId) {
        entity.setScore_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Score entity) {
        if(entity != null) {
            return entity.getScore_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Score entity) {
        return entity.getScore_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "scores" to-many relationship of Student. */
    public List<Score> _queryStudent_Scores(Long studentId) {
        synchronized (this) {
            if (student_ScoresQuery == null) {
                QueryBuilder<Score> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.StudentId.eq(null));
                student_ScoresQuery = queryBuilder.build();
            }
        }
        Query<Score> query = student_ScoresQuery.forCurrentThread();
        query.setParameter(0, studentId);
        return query.list();
    }

}
